import 'bootstrap/dist/css/bootstrap-reboot.css'
import 'gatsby-remark-vscode/styles.css'
import '@fortawesome/fontawesome-svg-core/styles.css'
import './src/styles/variables.css'
import './src/styles/layout.css'
