import 'bootstrap/dist/css/bootstrap-reboot.css'
import '@fortawesome/fontawesome-svg-core/styles.css'
import 'prismjs/themes/prism-tomorrow.css'
import './src/styles/variables.css'
import './src/styles/layout.css'
